name: Generate README using GitHub Actions

on:
  push:
    branches: [main, Borys]
    paths:
      - 'constitution.tex'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Option 1: Use pandoc-action
      - name: Convert LaTeX to Markdown
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            constitution.tex
            -o README.md
            --from=latex
            --to=markdown

      - name: Commit README to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-generate README.md from constitution.tex [skip ci]" || echo "No changes to commit"
          git push origin main 